/* eslint-disable */
// Generated by Wrangler from wrangler.jsonc. Run `wrangler types --include-runtime false` after binding changes.
interface __BaseEnv_Env {
	EMAIL: SendEmail;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
